const braveVesperia = [
{
    id: 0,
    name: "Yuri",
    img: "portraits/yuri.png",
    element: "DARK",
    weak: 'LIGHT',
    strong: 'n/a',
    weapon: "Sword",
    arte1: {
        type: 0,
        name: "Dragon Swarm",
        hits: 7,
        value: 1000,
        status: "none",
        cooldown: 3,
        turnsLeft: 0,
        isMultiTarget: false,
        isAvailable: true
    },
    arte2: {
        type: 0,
        name: "Divine Wolf",
        hits: 13,
        value: 490,
        status: "none",
        cooldown: 4,
        turnsLeft: 0,
        isMultiTarget: false,
        isAvailable: true
    },
    health: 22000,
    attack: 1.260,
    defense: .870,
    canAct: true,
    isAlive: true
}, {
    id: 1,
    name: "Estellise",
    img: "portraits/estelle.png",
    element: "LIGHT",
    weak: 'DARK',
    strong: 'n/a',
    weapon: "Staff",
    arte1: {
        type: 1,
        name: "First Aid",
        hits: 0,
        value: 5000,
        status: "none",
        cooldown: 2,
        turnsLeft: 0,
        isMultiTarget: false,
        isAvailable: true
    },
    arte2: {
        type: 0,
        name: "Holy Rain",
        hits: 5,
        value: 700,
        status: "none",
        cooldown: 3,
        turnsLeft: 0,
        isMultiTarget: true,
        isAvailable: true
    },
    health: 26000,
    attack: 1.055,
    defense: .650,
    canAct: true,
    isAlive: true
}, {
    id: 2,
    name: "Karol",
    img: "portraits/karol.png",
    element: "EARTH",
    weak: 'FIRE',
    strong: 'WIND',
    weapon: "Hammer",
    arte1: {
        type: 0,
        name: "Reaper Knock",
        hits: 1,
        value: 8500,
        status: "none",
        cooldown: 5,
        turnsLeft: 0,
        isMultiTarget: false,
        isAvailable: true
    },
    arte2: {
        type: 0,
        name: "Destruction Street",
        hits: 3,
        value: 2650,
        status: "none",
        cooldown: 4,
        turnsLeft: 0,
        isMultiTarget: false,
        isAvailable: true
    },
    health: 23000,
    attack: 1.200,
    defense: .770,
    canAct: true,
    isAlive: true
}, {
    id: 3,
    name: "Rita",
    img: "portraits/rita.png",
    element: "WATER",
    weak: 'WIND',
    strong: 'FIRE',
    weapon: "Artes",
    arte1: {
        type: 0,
        name: "Tidal Wave",
        hits: 5,
        value: 1000,
        status: "none",
        cooldown: 4,
        turnsLeft: 0,
        isMultiTarget: true,
        isAvailable: true
    },
    arte2: {
        type: 0,
        name: "Blade Roll",
        hits: 3,
        value: 2900,
        status: "none",
        cooldown: 4,
        turnsLeft: 0,
        isMultiTarget: true,
        isAvailable: true
    },
    health: 19000,
    attack: 1.500,
    defense: 0.980,
    canAct: true,
    isAlive: true
}, {
    id: 4,
    name: "Raven",
    img: "portraits/raven.png",
    element: "WIND",
    weak: 'EARTH',
    strong: 'WATER',
    weapon: "Bow",
    arte1: {
        type: 0,
        name: "Tempest",
        hits: 12,
        value: 300,
        status: "none",
        cooldown: 4,
        turnsLeft: 0,
        isMultiTarget: true,
        isAvailable: true
    },
    arte2: {
        type: 0,
        name: "Azure Heavens",
        hits: 5,
        value: 600,
        status: "none",
        cooldown: 3,
        turnsLeft: 0,
        isMultiTarget: true,
        isAvailable: true
    },
    health: 21000,
    attack: 1.100,
    defense: 0.830,
    canAct: true,
    isAlive: true
}, {
    id: 5,
    name: "Judith",
    img: "portraits/judith.png",
    element: "FIRE",
    weak: 'WATER',
    strong: 'EARTH',
    weapon: "Spear",
    arte1: {
        type: 0,
        name: "Moonbeam",
        hits: 2,
        value: 2290,
        status: "none",
        cooldown: 2,
        turnsLeft: 0,
        isMultiTarget: false,
        isAvailable: true
    },
    arte2: {
        type: 0,
        name: "Thunder Moon Rising",
        hits: 4,
        value: 1000,
        status: "none",
        cooldown: 3,
        turnsLeft: 0,
        isMultiTarget: true,
        isAvailable: true
    },
    health: 14000,
    attack: 1.300,
    defense: 0.550,
    canAct: true,
    isAlive: true
}, {
    id: 6,
    name: "Repede",
    img: "portraits/repede.png",
    element: "none",
    weak: 'n/a',
    strong: 'n/a',
    weapon: "Dagger",
    arte1: {
        type: 0,
        name: "Sonic Fang",
        hits: 51,
        value: 80,
        status: "none",
        cooldown: 5,
        turnsLeft: 0,
        isMultiTarget: false,
        isAvailable: true
    },
    arte2: {
        type: 0,
        name: "Ghost Wolf",
        hits: 10,
        value: 600,
        status: "none",
        cooldown: 6,
        turnsLeft: 0,
        isMultiTarget: true,
        isAvailable: true
    },
    health: 17000,
    attack: 1.400,
    defense: 0.900,
    canAct: true,
    isAlive: true
}, {
    id: 7,
    name: "Flynn",
    img: "portraits/flynn.png",
    element: "FIRE",
    weak: 'n/a',
    strong: 'EARTH',
    weapon: "Sword",
    arte1: {
        type: 0,
        name: "Rising Phoenix",
        hits: 3,
        value: 2100,
        status: "none",
        cooldown: 3,
        turnsLeft: 0,
        isMultiTarget: false,
        isAvailable: true
    },
    arte2: {
        type: 0,
        name: "Blazing Pillar Smash",
        hits: 12,
        value: 480,
        status: "none",
        cooldown: 4,
        turnsLeft: 0,
        isMultiTarget: false,
        isAvailable: true
    },
    health: 20000,
    attack: 1.350,
    defense: 0.670,
    canAct: true,
    isAlive: true
}, {
    id: 8,
    name: "Patty",
    img: "portraits/patty.png",
    element: "WATER",
    weak: 'n/a',
    strong: 'FIRE',
    weapon: "Dagger",
    arte1: {
        type: 0,
        name: "Little Big Chef",
        hits: 3,
        value: 1900,
        status: "none",
        cooldown: 2,
        turnsLeft: 0,
        isMultiTarget: false,
        isAvailable: true
    },
    arte2: {
        type: 0,
        name: "Random Fall",
        hits: 1,
        value: (Math.random() + 1.00) * 3500,
        status: "none",
        cooldown: 3,
        turnsLeft: 0,
        isMultiTarget: false,
        isAvailable: true
    },
    health: 22000,
    attack: 1.210,
    defense: 0.830,
    canAct: true,
    isAlive: true
}];

const baddies = [{
    id: 100,
    name: "Dark Polwigle",
    img: "./media/portraits/darkp.png",
    element: "DARK",
    weak: 'LIGHT',
    strong: 'n/a',
    health: 30000,
    attack: 3000,
    defense: 1.000,
    dead: false
}, {
    id: 101,
    name: "Light Polwigle",
    img: "./media/portraits/lightp.png",
    element: "LIGHT",
    weak: 'DARK',
    strong: 'n/a',
    health: 30000,
    attack: 3000,
    defense: 1.000,
    dead: false
}, {
    id: 102,
    name: "Earth Polwigle",
    img: "./media/portraits/earthp.png",
    element: "EARTH",
    weak: 'FIRE',
    strong: 'WIND',
    health: 50000,
    attack: 2000,
    defense: 1.000,
    dead: false
}, {
    id: 103,
    name: "Water Polwigle",
    img: "./media/portraits/waterp.png",
    element: "WATER",
    weak: 'WIND',
    strong: 'FIRE',
    health: 50000,
    attack: 2000,
    defense: 1.000,
    dead: false
}, {
    id: 104,
    name: "Wind Polwigle",
    img: "./media/portraits/windp.png",
    element: "WIND",
    weak: 'EARTH',
    strong: 'WATER',
    health: 50000,
    attack: 2000,
    defense: 1.000,
    dead: false
}, {
    id: 105,
    name: "Fire Polwigle",
    img: "./media/portraits/firep.png",
    element: "FIRE",
    weak: 'WATER',
    strong: 'EARTH',
    health: 50000,
    attack: 2000,
    defense: 1.000,
    dead: false
}];

const boss = {
    id: 200,
    name: "Grand Polwigle",
    img: "./media/portraits/boss.png",
    element: "none",
    weak: 'n/a',
    strong: 'n/a',
    health: 112699,
    attack: 4500,
    defense: 1.000
};
